# Generated by Django 3.2.8 on 2021-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddac_app', '0004_rename_fishid_fish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
