# Generated by Django 3.2.8 on 2021-11-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddac_app', '0006_fish_fishfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
