# Generated by Django 3.2.8 on 2021-11-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddac_app', '0007_alter_fish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
